[build]
  command = "npm run build"
  publish="dist"
  base = "packages/front/"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- packages/front/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200