[build]
  command = "npm run build"
  publish="dist"
  base = "packages/front"
  ignore = "packages/back"
  # The base directory should be the path to the nested Vue project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200