version: '3'
services:
  app:
    container_name: app
    restart: unless-stopped
    env_file: .env
    build: .
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=production
      - IP=0.0.0.0
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - OPENID_CLIENT_ID=$OPENID_CLIENT_ID
      - OPENID_CLIENT_SECRET=$OPENID_CLIENT_SECRET
    volumes:
      - dist:/app/dist
      - src:/app/src
      - node_modules:/app/node_modules
      - logs:/app/logs
    networks:
      - app-network

  mongo:
    container_name: mongo
    env_file: .env
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./dbdata:/data/db
    networks:
      - app-network

  # redis:
  #   container_name: redis
  #   image: 'redis:alpine'
  #   networks:
  #     - app-network
  #   ports:
  #     - "6379:6379"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
  dist:
  src:
  logs:
